name: Setup project
description: Install the pinned toolchain and project dependencies

runs:
  using: composite
  steps:
    - name: Setup toolchain
      uses: moonrepo/setup-toolchain@v0
      with:
        auto-install: true
        cache: false

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
